# global parameters
numworkers = 8
numepochs = 300
roboflowurl = 'https://app.roboflow.ai/ds/nw1nLjWUAM?key=4svwFCyLJM'
yolotype = '/cfg/yolov3-tiny.cfg'
numbatches = 64
numaccums = 2
imagesize = 416
weightsfile = 'yolov3-spp-ultralytics.pt'
batchsize = 64
